server:
  port: 6800

spring:
  application:
    name: com.yi.nuo.manage.api
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB


#spring doc 配置
springdoc:
  description:
    application-name: 懿诺后台管理系统
    application-version: 1.0
    application-description: 懿诺后台管理系统openapi整合
    try-host: http://localhost:${server.port}
  swagger-ui:
    path: /springdoc/docs.html
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /springdoc/api-docs
    resolve-schema-properties: true
  writer-with-default-pretty-printer: true

